//Question 1
//  let num1 = prompt("Enter the first number: ");
//  let num2 = prompt("Enter the second number: ");

//  if (num1 > num2) {
//    console.log(num1 + " is larger than " + num2);
//  } else if (num2 > num1) {
//    console.log(num2 + " is larger than " + num1);
//  } else {
//    console.log("Both numbers are equal");
//  }
//End of Question 1

//Question 2
// let num = prompt("Enter a number:");
// if (num > 0) {
//   alert("The sign is +");
// } else if (num < 0) {
//   alert("The sign is -");
// } else {
//   alert("The number is 0");
// }
//End of Question 2


// //Question 3
//   let num1 =+prompt("Enter number 1:");
//   let num2 =+prompt("Enter number 2:");
//   let num3 =+prompt("Enter number 3:");
//   let num4 =+prompt("Enter number 4:");
//   let num5 =+prompt("Enter number 5:");
//   let largest = num1;

//  if (num2 > largest) {
//    largest = num2;
//  }
//  else if (num3 > largest) {
//    largest = num3;
//  }
//  else if (num4 > largest) {
//    largest = num4;
//  }
//  else {(num5 > largest) 
//    largest = num5;
//  }

//  console.log("The largest number is " + largest);

//End of Question 3


//Question no 4
  // for (let i = 0; i <= 15; i++){
  //   if (i % 2 === 0) {
  //     console.log(i + " is even");
  //   } else {
  //     console.log(i + " is odd");
  //   }
  // }

//End of Question 4


//Question no 5
// let userMarks=+prompt("Enter your percentage");

// let grade;
// if (userMarks < 60) {
//   grade = "F";
//   console.log( userMarks+" percent" +" your grade is " + grade );
// } else if (userMarks < 70) {
//   grade = "D";
//   console.log(userMarks+" percent" +" your grade is " + grade );
// } else if (userMarks < 80) {
//   grade = "C";
//   console.log(userMarks+" percent" +" your grade is " + grade );
// } else if (userMarks < 90) {
//   grade = "B";
//   console.log(userMarks+" percent" +" your grade is " + grade );
// } else {
//   grade = "A";
//   console.log("Congratulations" +" your grade is " + grade);
// }
//End of Question 5


//Question no 6
//  for (let i = 1; i <= 100; i++) {
//    if (i % 3 === 0 && i % 5 === 0) {
//      console.log("FizzBuzz");
//    } else if (i % 3 === 0) {
//      console.log( "Fizz");
//    } else if (i % 5 === 0) {
//      console.log("Buzz");
//     }  else {
//      console.log(i);
//     }
//  }
//End Question 6


//Question no 7
//  for (let i = 1; i <= 5; i++) {
//    let line = "";
//    for (let j = 1; j <= i; j++) {
//     line += "* ";
//    }
//  console.log(line);
//  }
//End Question 7













































// 
     































































































































    // }